server:
    port: 8085
    servlet:
        context-path: /store
spring:
    h2:
        console:
            enabled: true #Enabling H2 Console. Make sure to use jdbc:h2:mem:testdb as JDBC URL when connecting to the console
            path: '/h2'
    jpa:
        hibernate:
            ddl-auto: none #This will allow usage of schema.sql versus entity classes
        properties:
            hibernate:
                format_sql: true
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
logging:
    level:
          org:
              hibernate:
                        type:
                              descriptor:
                                          sql:  TRACE